# config.yaml

# === SERIAL PORT SETTINGS ===
serial:
  port: "COM5"
  baud_rate: 500000

# === AUDIO / SAMPLING SETTINGS ===
audio:
  sample_rate: 22050
  block_size: 512


# === WINDOW CALCULATED ===
window:
  size: 44100               # sample_rate * window_duration
  step: 22050               # sample_rate * step_duration

# === LOGGING SETTINGS ===
logging:
  log_dir: "Logs"

# === COMPONENT NAMES ===
components:
  - mast
  - elevator
  - gripper
  - shuttle
  - environment
  - mast bearing broken

# === MODEL PATHS ===
models:
  classification_model: "model_files/lgb.joblib"
  # Optional feature scaler (e.g., StandardScaler). If not present, features are used as-is.

# === DB/OCSVM THRESHOLDS ===
db:
  calib_offset: 0        # additional field calibration offset (dB)
  threshold: 88
  method: "ref"
  ref_rms: 20e-6

ocsvm:
  threshold: -0.2   # decision_function score threshold


testers:
  name: "IPC1"

batch:
  size: 30
  wav_dir: "wav_file_temp"

mfcc:
  n_mfcc: 13

# === UI OPTIONS ===
ui:
  spinner_enabled: true
  spinner_interval: 0.3