# config.yaml

# === SERIAL PORT SETTINGS ===
serial:
  port: "COM5"
  baud_rate: 500000

# === AUDIO / SAMPLING SETTINGS ===
audio:
  sample_rate: 22050
  block_size: 512


# === WINDOW CALCULATED ===
window:
  size: 44100               # sample_rate * window_duration
  step: 22050               # sample_rate * step_duration

# === LOGGING SETTINGS ===
logging:
  log_dir: "Logs"

# === COMPONENT NAMES ===
components:
  - mast
  - elevator
  - gripper
  - shuttle
  - environment

# === MODEL PATHS ===
models:
  ocsvm: "model_files/ocsvm_model.joblib"
  log_reg: "model_files/log_reg_model.joblib"
  # Optional feature scaler (e.g., StandardScaler). If not present, features are used as-is.
  scaler: "model_files/scaler.joblib"

# === DB/OCSVM THRESHOLDS ===
db:
  calib_offset:         # additional field calibration offset (dB)
  normal_max: 87.0         # dB < normal_max => Normal (skip OCSVM)
  anomaly_min: 88.0        # dB > anomaly_min => Anomaly (skip OCSVM)

ocsvm:
  threshold: -0.8   # decision_function score threshold


testers:
  name: "RPB1"

batch:
  size: 10
  wav_dir: "wav_file_temp"

mfcc:
  n_mfcc: 13

# === UI OPTIONS ===
ui:
  spinner_enabled: true
  spinner_interval: 0.3